// Dream House Profile Types

export type AreaType = 'urban' | 'suburban' | 'rural' | 'flexible'
export type BudgetFlexibility = 'strict' | 'flexible' | 'very_flexible'
export type PaymentType = 'financing' | 'cash' | 'mixed'
export type OutdoorSpace = 'yard' | 'balcony' | 'terrace' | 'rooftop' | 'garden' | 'pool_area'
export type FloorType = 'single' | 'multi' | 'apartment' | 'any'
export type AgePreference = 'new' | 'up_to_10' | 'up_to_20' | 'any'
export type RenovationWillingness = 'none' | 'minor' | 'major' | 'full'
export type FinishingLevel = 'high' | 'medium' | 'willing_to_renovate'
export type WorkFromHome = 'never' | 'sometimes' | 'always'
export type EntertainFrequency = 'rarely' | 'sometimes' | 'often'
export type Urgency = 'asap' | '3_months' | '6_months' | '1_year' | 'flexible'
export type ViewPreference = 'city' | 'nature' | 'ocean' | 'mountains' | 'any'
export type SecurityImportance = 1 | 2 | 3 | 4 | 5
export type LightImportance = 1 | 2 | 3 | 4 | 5

// Location preferences
export interface LocationPreferences {
  cities: string[]
  neighborhoods: string[]
  areaType: AreaType
  proximityNeeds: string[]
  securityImportance: SecurityImportance
  viewPreference: ViewPreference
}

// Budget preferences
export interface BudgetPreferences {
  min: number | null
  max: number | null
  flexibility: BudgetFlexibility
  paymentType: PaymentType
  monthlyBudget?: number | null
}

// Size preferences
export interface SizePreferences {
  bedroomsMin: number
  bedroomsIdeal: number
  bathroomsMin: number
  sqftMin: number | null
  sqftIdeal?: number | null
  outdoorSpace: OutdoorSpace[]
  parkingSpots: number
  floors: FloorType
}

// Features preferences
export interface FeaturesPreferences {
  mustHave: string[]
  niceToHave: string[]
  dealBreakers: string[]
}

// Style preferences
export interface StylePreferences {
  architectural: string[]
  agePreference: AgePreference
  renovationWillingness: RenovationWillingness
  finishingLevel: FinishingLevel
  naturalLightImportance: LightImportance
}

// Lifestyle preferences
export interface LifestylePreferences {
  worksFromHome: WorkFromHome
  hasChildren: boolean
  childrenCount?: number
  childrenAges?: string[]
  hasPets: boolean
  petTypes?: string[]
  entertainsGuests: EntertainFrequency
  hobbiesNeedingSpace: string[]
}

// Timeline preferences
export interface TimelinePreferences {
  urgency: Urgency
}

// Buyer Persona generated by AI
export interface BuyerPersona {
  narrative: string
  searchPrompt: string
  matchingCriteria: string[]
  summary: string
}

// Complete Dream House Profile
export interface DreamHouseProfileData {
  location: LocationPreferences
  budget: BudgetPreferences
  size: SizePreferences
  features: FeaturesPreferences
  style: StylePreferences
  lifestyle: LifestylePreferences
  timeline: TimelinePreferences
  buyerPersona?: BuyerPersona
  completedSteps: number[]
  isWizardComplete: boolean
  completedAt?: Date
}

// Wizard step configuration
export interface WizardStepConfig {
  id: number
  title: string
  description: string
  icon: string
  isOptional?: boolean
}

// Wizard step props
export interface WizardStepProps<T> {
  data: T
  onChange: (data: T) => void
  onValidate?: () => boolean
  errors?: Record<string, string>
}

// Chat message for refinement
export interface ChatMessage {
  role: 'user' | 'assistant'
  content: string
  timestamp?: Date
}

// Feature option for chips
export interface FeatureOption {
  id: string
  label: string
  category: 'essential' | 'desirable' | 'dealbreaker'
  icon?: string
}

// Predefined feature options
export const FEATURE_OPTIONS: FeatureOption[] = [
  // Essentials
  { id: 'pool', label: 'Pool', category: 'essential' },
  { id: 'bbq_area', label: 'BBQ / Outdoor Kitchen', category: 'essential' },
  { id: 'high_ceiling', label: 'High Ceilings', category: 'essential' },
  { id: 'master_suite', label: 'Master Suite', category: 'essential' },
  { id: 'home_office', label: 'Home Office', category: 'essential' },
  { id: 'walk_in_closet', label: 'Walk-in Closet', category: 'essential' },
  { id: 'central_ac', label: 'Central AC', category: 'essential' },
  { id: 'heating', label: 'Heating System', category: 'essential' },
  { id: 'laundry_room', label: 'Separate Laundry', category: 'essential' },
  { id: 'pantry', label: 'Pantry', category: 'essential' },
  { id: 'garage', label: 'Covered Garage', category: 'essential' },
  { id: 'security_system', label: 'Security System', category: 'essential' },

  // Desirable
  { id: 'garden', label: 'Garden / Landscaping', category: 'desirable' },
  { id: 'smart_home', label: 'Smart Home', category: 'desirable' },
  { id: 'solar_energy', label: 'Solar Panels', category: 'desirable' },
  { id: 'bathtub_spa', label: 'Bathtub / Spa', category: 'desirable' },
  { id: 'wine_cellar', label: 'Wine Cellar', category: 'desirable' },
  { id: 'gym', label: 'Home Gym', category: 'desirable' },
  { id: 'game_room', label: 'Game Room', category: 'desirable' },
  { id: 'home_theater', label: 'Home Theater', category: 'desirable' },
  { id: 'guest_suite', label: 'Guest Suite', category: 'desirable' },
  { id: 'fireplace', label: 'Fireplace', category: 'desirable' },
  { id: 'elevator', label: 'Elevator', category: 'desirable' },
  { id: 'sauna', label: 'Sauna', category: 'desirable' },

  // Deal Breakers
  { id: 'no_elevator_high', label: 'No Elevator (High Floor)', category: 'dealbreaker' },
  { id: 'busy_street', label: 'Busy Street', category: 'dealbreaker' },
  { id: 'commercial_neighbor', label: 'Commercial Neighbor', category: 'dealbreaker' },
  { id: 'no_outdoor', label: 'No Outdoor Space', category: 'dealbreaker' },
  { id: 'old_no_renovation', label: 'Old Without Renovation', category: 'dealbreaker' },
  { id: 'no_natural_light', label: 'Poor Natural Light', category: 'dealbreaker' },
  { id: 'no_parking', label: 'No Parking Space', category: 'dealbreaker' },
  { id: 'hoa_restrictions', label: 'Heavy HOA Restrictions', category: 'dealbreaker' },
]

// Architectural styles
export const ARCHITECTURAL_STYLES = [
  { id: 'modern', label: 'Modern' },
  { id: 'contemporary', label: 'Contemporary' },
  { id: 'minimalist', label: 'Minimalist' },
  { id: 'traditional', label: 'Traditional' },
  { id: 'colonial', label: 'Colonial' },
  { id: 'rustic', label: 'Rustic' },
  { id: 'industrial', label: 'Industrial' },
  { id: 'mediterranean', label: 'Mediterranean' },
  { id: 'craftsman', label: 'Craftsman' },
  { id: 'mid_century', label: 'Mid-Century' },
]

// Proximity options
export const PROXIMITY_OPTIONS = [
  { id: 'work', label: 'Work' },
  { id: 'schools', label: 'Schools' },
  { id: 'public_transport', label: 'Public Transit' },
  { id: 'shopping', label: 'Shopping' },
  { id: 'hospitals', label: 'Hospitals' },
  { id: 'parks', label: 'Parks' },
  { id: 'gym', label: 'Gym' },
  { id: 'restaurants', label: 'Restaurants' },
  { id: 'beach', label: 'Beach' },
  { id: 'airport', label: 'Airport' },
]

// Pet types
export const PET_TYPES = [
  { id: 'dog_small', label: 'Small Dog' },
  { id: 'dog_large', label: 'Large Dog' },
  { id: 'cat', label: 'Cat' },
  { id: 'bird', label: 'Bird' },
  { id: 'fish', label: 'Fish' },
  { id: 'other', label: 'Other' },
]

// Hobby options that need space
export const HOBBY_OPTIONS = [
  { id: 'home_gym', label: 'Home Gym' },
  { id: 'music', label: 'Music / Instruments' },
  { id: 'gardening', label: 'Gardening' },
  { id: 'woodworking', label: 'Woodworking' },
  { id: 'art', label: 'Art / Painting' },
  { id: 'gaming', label: 'Gaming' },
  { id: 'yoga', label: 'Yoga / Meditation' },
  { id: 'wine', label: 'Wine' },
  { id: 'cooking', label: 'Cooking' },
  { id: 'cars', label: 'Cars / Motorcycles' },
]

// Default empty profile
export const DEFAULT_PROFILE: DreamHouseProfileData = {
  location: {
    cities: [],
    neighborhoods: [],
    areaType: 'flexible',
    proximityNeeds: [],
    securityImportance: 3,
    viewPreference: 'any',
  },
  budget: {
    min: null,
    max: null,
    flexibility: 'flexible',
    paymentType: 'financing',
    monthlyBudget: null,
  },
  size: {
    bedroomsMin: 2,
    bedroomsIdeal: 3,
    bathroomsMin: 2,
    sqftMin: null,
    sqftIdeal: null,
    outdoorSpace: [],
    parkingSpots: 1,
    floors: 'any',
  },
  features: {
    mustHave: [],
    niceToHave: [],
    dealBreakers: [],
  },
  style: {
    architectural: [],
    agePreference: 'any',
    renovationWillingness: 'minor',
    finishingLevel: 'medium',
    naturalLightImportance: 4,
  },
  lifestyle: {
    worksFromHome: 'sometimes',
    hasChildren: false,
    childrenCount: 0,
    childrenAges: [],
    hasPets: false,
    petTypes: [],
    entertainsGuests: 'sometimes',
    hobbiesNeedingSpace: [],
  },
  timeline: {
    urgency: 'flexible',
  },
  completedSteps: [],
  isWizardComplete: false,
}

// Wizard steps configuration
export const WIZARD_STEPS: WizardStepConfig[] = [
  {
    id: 1,
    title: 'Location',
    description: 'Where do you want to live?',
    icon: 'location',
  },
  {
    id: 2,
    title: 'Budget',
    description: 'What is your investment?',
    icon: 'money',
  },
  {
    id: 3,
    title: 'Size',
    description: 'Ideal space',
    icon: 'size',
  },
  {
    id: 4,
    title: 'Features',
    description: 'What must it have?',
    icon: 'features',
  },
  {
    id: 5,
    title: 'Style',
    description: 'Your preferences',
    icon: 'style',
  },
  {
    id: 6,
    title: 'Lifestyle',
    description: 'Your daily life',
    icon: 'lifestyle',
  },
]

// Validation helpers
export function validateLocationStep(data: LocationPreferences): Record<string, string> {
  const errors: Record<string, string> = {}
  if (data.cities.length === 0) {
    errors.cities = 'Select at least one city'
  }
  return errors
}

export function validateBudgetStep(data: BudgetPreferences): Record<string, string> {
  const errors: Record<string, string> = {}
  if (data.min && data.max && data.min > data.max) {
    errors.budget = 'Minimum value must be less than maximum'
  }
  return errors
}

export function validateSizeStep(data: SizePreferences): Record<string, string> {
  const errors: Record<string, string> = {}
  if (data.bedroomsMin < 1) {
    errors.bedrooms = 'Minimum of 1 bedroom'
  }
  if (data.bathroomsMin < 1) {
    errors.bathrooms = 'Minimum of 1 bathroom'
  }
  return errors
}

export function isProfileComplete(profile: DreamHouseProfileData): boolean {
  return profile.completedSteps.length === WIZARD_STEPS.length
}
